services:
  customer_feedback_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer_feedback_service
    ports:
      - "8080:8080"
    depends_on:
      - feedback_db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@feedback_db:27017/feedback?authSource=admin

  feedback_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=feedback
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  customer_feedback_service_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: customer_feedback_service_test
    entrypoint: ["./gradlew", "test"]
    working_dir: $PWD
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb_data:
    driver: local
