
services:
  customer_feedback_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer_feedback_service
    ports:
      - "8080:8080"
    depends_on:
      - feedback_db
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://recipes_db:5432/recipes_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true


  recipes_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  customer_feedback_service_test:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: customer_feedback_service_test
    entrypoint: ["./gradlew", "test"]
    working_dir: $PWD
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
